# small base image
FROM python:3.7.4-alpine

WORKDIR /usr/src/app

# set environment varibles

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV production
ENV APP_SETTINGS project.config.ProductionConfig


COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# run server
CMD gunicorn --bind 0.0.0.0:$PORT manage:app
